/**
 * Every word NivPay shows people lives here.
 *
 * Product rule (docs/BUILD-APP.md): NivPay reads like a fintech app. People
 * never need to know it runs on crypto. No crypto, blockchain, block, chain,
 * onchain, wallet, token, gas, Monad, testnet, network, address, hash,
 * contract, stablecoin, seed, mnemonic, private key, 0x or MON, in any form.
 * copy.test.ts enforces this on this file and on the text in the screens.
 *
 * The only exception is data, not wording: the Account ID in the account
 * details sheet shows the account's identifier so support can find it.
 */

export const copy = {
  appName: "NivPay",
  tagline: "A group purse for one purpose that no single person can pocket.",
  testMode: "Test mode",

  // Welcome, sign up, sign in, switch account
  switchAccount: "Switch account",
  accountsOnThisPhone: "Accounts on this phone",
  useOneOfThese: "Use one of these",
  pickAccountHint: "Your phone asks which passkey. Pick the account you want.",
  addAnotherAccount: "Add another account",
  makeYourAccount: "Make your account",
  yourName: "Your name",
  namePlaceholder: "Idara",
  createAccount: "Create your account",
  createAccountHint: "Your account is a passkey on this phone. There is no password and nothing to write down.",
  alreadyHaveAccount: "I already have an account",
  waitingForPasskey: "Waiting for your passkey…",
  back: "Back",

  // Account home
  accountDetails: "Account details",
  accountId: "Account ID",
  accountIdHint: "Only needed if NivPay support asks for it.",
  viewReceipt: "View receipt",
  viewReceiptHint: "Your latest payment or claim, on a public record anyone can check.",
  copyAction: "Copy",
  copied: "Copied",
  close: "Close",
  yourBalance: "Your balance",
  readingBalance: "Reading your balance…",
  dollars: "Dollars",
  dollarsLine: "Held as AUSD, a digital dollar issued by Agora.",
  testDollars: "Test dollars",
  testDollarsLine: "Test dollars, not real money.",

  // Add test dollars
  addTestDollars: "Add test dollars",
  addTestDollarsHint: "For trying NivPay out. These are test dollars, not real money, and they only work in test mode.",
  howMany: "How many",
  upToAtATime: (max: string) => `Up to ${max} at a time.`,
  stepPreparing: "Getting ready…",
  stepGettingReady: "Getting your account ready…",
  stepConfirm: "Confirm with your fingerprint",
  stepSending: "Adding test dollars…",
  added: (amount: string, seconds: string) => `Added ${amount} test dollars. Settled in ${seconds}s.`,
  tryAgain: "Try again",
  claimAmountHint: (amount: string, ceiling: string) =>
    `Adds ${amount} each time, once a minute at most. You can hold up to ${ceiling} this way.`,
  errClaimCooldown: (seconds: number) =>
    `Test dollars can be added once a minute, and someone just did. Try again in ${seconds} ${seconds === 1 ? "second" : "seconds"}.`,
  claimCooldownOver: "You can try again now.",
  errClaimCeiling:(ceiling: string) => `You already hold ${ceiling} or more, the most you can add this way.`,
  errClaimRefused: "Test dollars can't be added right now. Try again in a minute.",
  claimDidNotGoThrough: "That didn't go through. No test dollars moved. Try again in a minute.",

  // Connection. "Nothing has moved" only when no request of ours is in flight.
  offlineNothingInFlight: "Can't connect right now. Nothing has moved. Trying again.",
  offlineRequestInFlight:
    "Can't connect right now. Your request was sent and is still being confirmed. Don't send it again. Trying again.",

  // Hosts
  onlyAtHome: (home: string) => `Accounts can only be made and used at ${home}. This copy of NivPay is for testing and can't hold an account.`,
  homeNotChosen: "Accounts can't be made here yet. NivPay's home hasn't been chosen, and an account made here could never move.",

  // Outcomes and failures. Each failure ends with its code from ERROR_CODES.
  nothingWasSent: "Nothing was sent.",
  sentNotConfirmed: "Your request was sent but isn't confirmed yet. Don't send it again: NivPay keeps checking and will show the result here.",
  stuck: "This is taking longer than it should. It hasn't gone through, and nothing has moved yet.",
  earlierStuck: "An earlier attempt is taking longer than it should. It hasn't gone through, and nothing has moved yet.",
  didNotGoThrough: "That didn't go through. No test dollars moved.",
  code: (n: number) => `Code ${n}`,

  errPreparing: "Couldn't get this ready.",
  errInFlight: "Another payment from this account is still going through. Wait for it to finish.",
  errSetupUnreachable: "Couldn't reach NivPay to get your account ready. Check your connection and try again.",
  errSetupPaused: "NivPay can't set up payments right now. Try again later.",
  errSetupFailed: "Your account couldn't be made ready for this. Try again in a minute.",
  errSetupSlow: "Getting your account ready is taking too long. Try again in a minute.",
  errSetupReverted: "Getting your account ready didn't go through. Try again.",
  errPasskeyCancelled: "The passkey step was cancelled or didn't finish.",
  errPasskeyUnsupported:
    "This passkey can't hold a NivPay account. On Android, save it to Google Password Manager. " +
    "On iPhone, use iCloud Keychain on iOS 18 or later. Chrome's desktop profile, Bitwarden and Dashlane don't work. " +
    "If you use Samsung Pass, choose Google Password Manager instead.",
  errBrowserMissingFeature: "This browser is missing a security feature NivPay needs. Update Chrome and try again.",
  errWrongPasskey: "That passkey belongs to a different NivPay account. Choose the passkey for this account and try again.",
  errPasskeyTimedOut: "The signing step timed out.",
  errPasskeyOther: "Something went wrong with the passkey.",
  errSigning: "Couldn't sign this request.",
  errSaving: "Couldn't save this request on your phone.",
  errConfirming: "Your request was sent but checking on it failed.",
  errMayStillGoThrough: "The earlier attempt may still go through. Wait a little longer.",
  errNothingStuck: "There's nothing waiting to try again.",
  errUnknown: "Something went wrong.",

  // Your pots, on the account home
  yourPots: "Your pots",
  makeAPot: "Make a pot",
  noPotsYet: "No pots yet. Make one for a party, a trip or a shared bill.",
  unnamedPot: "Unnamed pot",
  draft: "Draft",
  live: "Live",
  potRowDraft: (people: number) => `Not made yet. ${people} ${people === 1 ? "person" : "people"} so far.`,
  potRowMade: (date: string) => `Made. Closes ${date}.`,

  // Make a pot (Live-Create)
  newPot: "New pot",
  potTitle: (name: string) => `A pot for ${name}`,
  nameYourPot: "Name your pot",
  createLede: "Choose who decides, where it can pour, and when it closes.",
  whoDecides: "Who decides",
  poursOnlyTo: "Pours only to",
  closes: "Closes",
  leftover: "Leftover",
  leftoverValue: "Back to each of you, by share",
  ofN: (k: number, n: number) => `${k} of ${n}`,
  justYouSoFar: "Just you so far",
  addWhereItPays: "Add where it can pay",
  chooseADate: "Choose a date",
  upTo: (amount: string) => `up to ${amount}`,
  morePayees: (n: number) => `and ${n} more`,
  lockBefore: "Once it's made, nobody can change where it pours. Not even you.",
  lockAfter: "Locked. Nobody can change where it pours, not even you.",
  makeThePot: "Make the pot",
  draftNotMade: "Draft, not made yet",
  progressNobody: "Nobody invited yet. Invite who decides and add where it pays.",
  progressAllReplied: (names: string) => `Everyone has replied: ${names}.`,
  progressWaiting: (names: string) => `Waiting for a reply from ${names}.`,
  progressSome: (replied: string, waiting: string) => `Replied: ${replied}. Waiting for ${waiting}.`,
  createReady: "Everyone has replied. Check the details, then make the pot.",
  createSending: "Sending…",
  createConfirming: "Confirming…",
  createWaiting: "Sent and waiting to be confirmed, usually a few seconds. It isn't a pot until then.",
  checkAgain: "Check again",
  inThePot: "in the pot",
  personYou: (name: string) => `${name} · you`,
  personDecides: (name: string) => `${name} · decides`,
  morePeople: (n: number) => `+${n} more`,
  stillNeeded: (items: string) => `Still needed: ${items}.`,
  missingName: "a name",
  missingCity: "your city",
  missingDeciders: "a rule for who decides",
  missingReplies: "a reply from everyone you invited to decide",
  missingPayees: "somewhere it can pay, with a limit",
  missingPayeeAccount: "an account for each place it pays",
  missingCloses: "a closing date",
  missingClosesPast: "a closing date in the future",
  readingPotRules: "Reading the rules for new pots…",
  potMadeAlone: "Pot made. Share the link with anyone who'll chip in.",
  namesNeedSigning: "Pot made. Confirm once more to add everyone's names to the link, then you can share it.",
  signTheNames: "Add the names",
  potMadeAnnounce: (name: string, payees: string) => `${name} is made. It can only pay ${payees}.`,
  shareInviteLink: "Share the invite link",
  namedSeeItTitle: "No link needed for them",
  namedSeeIt: (names: string) => `${names} already have this pot on their Home. They don't need a link.`,
  shareThePot: "Share the pot",
  shareThePotHint: "Share the pot makes one link for the whole group: for everyone else who'll chip in, and for anyone who wants to see everyone's names.",
  sendAgain: "Send again",
  shareText: (name: string) => `Open our pot for ${name} on NivPay.`,
  linkCopied: "Link copied. Paste it in your chat.",
  copyFailed: "Couldn't copy the link. Press and hold it to copy it yourself.",
  createRefused: "The pot can't be made as it's set up. Check the closing date and try again.",
  createDidNotGoThrough: "That didn't go through. The pot wasn't made and nothing moved.",
  createDropped: "That was dropped before it went through. The pot isn't made and nothing has moved. You can try again.",
  createTurnedDown: "That was turned down before it went through. The pot isn't made and nothing has moved. You can try again.",
  done: "Done",
  map: (people: string, payees: string) => `Map: ${people} around the pot. The pot can only pour to ${payees}.`,
  nobodyYet: "nobody yet",

  // Sheets on the make a pot screen
  potName: "Pot name",
  potNamePlaceholder: "Mama's 60th",
  potNameHint: "Keep it short: up to 32 letters, fewer with accents or emoji.",
  potNameTooLong: "That name is too long.",
  yourCity: "Your city",
  cityPlaceholder: "London",
  theirCity: "City",
  timeZoneLine: (zone: string) => `Times show in ${zone}.`,
  decidersLede: "Deciders say yes to each payment. Send each of them your link, and add the reply they send back.",
  you: "you",
  inviteToDecide: "Invite someone to decide",
  inviteeName: "Their name",
  howManyMustSayYes: "How many must say yes",
  fewer: "Fewer",
  more: "More",
  ruleLine: (k: number, n: number) => `${k} of ${n} must say yes to each payment.`,
  remove: "Remove",
  payeesLede: "The pot can only ever pay these, each up to its limit. Nobody can change this list once the pot is made.",
  payeeName: "Who it pays",
  payeeNamePlaceholder: "Caterer",
  payeeNameTooLong: "That name is too long.",
  limit: "Up to",
  limitInvalid: "Enter an amount above $0.",
  addPlaceToPay: "Add a place to pay",
  add: "Add",
  waitingForReply: "Waiting for their reply",
  sendThemALink: "Send them a link",
  pasteTheirAccountId: "Paste their Account ID",
  theirAccountId: "Their Account ID",
  accountIdInvalid: "That isn't a NivPay Account ID. Check it and paste it again.",
  typeLast4: "Type its last 4 characters to confirm",
  typeLast4Hint: "Where it pays can never change, so check this against what they sent you.",
  last4Wrong: "Those don't match. Check the Account ID again.",
  useThisAccount: "Use this account",
  replyLinkField: "Got a reply link? Paste it here",
  addReply: "Add their reply",
  closesLede: "At the end of this day, in your time, nobody can put more in or pay from it. What's left goes back to each of you.",
  leftoverLede:
    "When the pot closes, whatever is left goes back to everyone who put money in, in proportion to what each put in. " +
    "Anyone can also take their own share out before then.",
  checkBeforeYouMakeIt: "Check it before you make it",
  noneCanChange: "None of this can ever change, not even by you.",
  decidesLine: "Decides",
  paysLine: (limit: string) => `Can be paid up to ${limit}`,
  suggestsLine: (amount: string) => `Suggested share ${amount}`,
  suggestedShare: "Suggested share",
  suggestedShareOptional: "Suggested share, if they chip in too",
  noSuggestion: "No suggestion",
  closesOn: (date: string) => `Closes at the end of ${date}`,

  // Pour in your share (Live-ChipIn)
  addYourShare: "Add your share",
  invitedYou: (from: string, pot: string) => `${from} invited you to help pay for ${pot}.`,
  yourOwnPot: (pot: string) => `Put your own share into ${pot}.`,
  invitedToPot: (pot: string) => `You were invited to help pay for ${pot}.`,
  less: "Less",
  exactAmount: "Exact amount",
  chipPoursOnlyTo: (names: string) => `Pours only to ${names}`,
  chipRule: (k: number, n: number) => `${k} of ${n} must agree`,
  chipLeftover: "Leftover comes back to you",
  pourIn: (amount: string) => `Pour in ${amount}`,
  pouringIn: "Pouring in…",
  fromYourBalance: (amount: string) => `From your balance of ${amount}.`,
  moreThanBalance: (amount: string) => `That's more than your balance of ${amount}. Add test dollars from your account first.`,
  pouredIn: (others: string) => `Poured in. ${others} will see it when they open the pot.`,
  pouredInAlone: "Poured in.",
  pourDidNotGoThrough: "That didn't go through. Nothing moved.",
  potClosedNote: "This pot is closed. Nothing more can go in.",
  potPausedNote: "Payments and pour-ins are paused on this pot.",
  personNotYet: (name: string) => `${name} · not yet`,
  personPutIn: (name: string, amount: string) => `${name} · ${amount}`,
  youCap: "You",
  someoneElse: "Someone",
  namesUnchecked: "Names couldn't be checked, so people are shown by the end of their account.",
  addedAnnounce: (name: string, amount: string, total: string) => `${name} added ${amount}. The pot has ${total}.`,
  mapPutIn: (name: string, amount: string, city: string) => `${name} put in ${amount} from ${city}.`,
  mapNotYet: (name: string, city: string) => `${name} in ${city} hasn't added yet.`,
  mapHolds: (amount: string) => `Map: the pot holds ${amount}.`,
  openingPot: "Opening the pot…",
  errPotUnreachable: "Couldn't read this pot right now. Check your connection and try again.",
  errPotOtherVersion: "This pot belongs to a different version of NivPay and can't be opened here.",
  errPotNotFound: "This pot couldn't be found. Ask for the link again.",
  potRowJoined: "Open to chip in and follow it.",
  addedToAPot: "Added to a pot",
  foundRoleDecides: "you decide on payments",
  foundRolePaid: "it can pay you",
  foundRolePutIn: "you've put money in",
  foundMeta: (roles: string[], holds: string) => {
    const who = new Intl.ListFormat("en-GB", { style: "long", type: "conjunction" }).format(roles);
    return `${who.charAt(0).toUpperCase()}${who.slice(1)}. Holds ${holds}.`;
  },
  foundNeedsLink: "Ask whoever made this pot to send you its link. Then you'll see everyone's names and can add your share.",
  closedTag: "Closed",
  errFindPots: "Couldn't check for pots you've been added to. Trying again.",

  // Send and receive
  sendDollars: "Send dollars",
  receive: "Receive",
  sendTitle: "Send dollars",
  sendTo: "Send to",
  sendToHint: "Open their request link, or paste their Account ID. They'll find it under Account details.",
  pasteAccountId: "Account ID",
  confirmLast4: "To be sure, type its last 4 characters",
  last4Mismatch: "Those aren't its last 4 characters.",
  notAnAccountId: "That isn't an Account ID. Ask them to copy it again from Account details.",
  sendingTo: (name: string) => `Sending to ${name}`,
  changeRecipient: "Change",
  howMuch: "How much",
  yourBalanceIs: (amount: string) => `Your balance is ${amount}.`,
  requestedAmount: (amount: string) => `They asked for ${amount}.`,
  reviewSend: "Review",
  confirmSendTitle: "Check and send",
  confirmTo: "To",
  confirmAmount: "Amount",
  confirmFee: "Fee",
  noFee: "None. NivPay covers it.",
  confirmArrives: "Arrives",
  arrivesInSeconds: "In about a second, final once confirmed",
  sendAction: (amount: string) => `Send ${amount}`,
  sentTitle: (amount: string, name: string) => `Sent ${amount} to ${name}`,
  settledIn: (seconds: string) => `Settled in ${seconds}s.`,
  sendAnother: "Send more",
  sendStillConfirming: "A payment you sent is still being confirmed. Follow it",
  sentEyebrow: "Payment final",
  stepSendingPayment: "Sending…",
  stepSettling: "Confirming…",
  sendDidNotGoThrough: "That payment didn't go through. Nothing moved.",
  sendFromRequest: (name: string) => `${name} asked you to pay them.`,
  errSendToSelf: "That's your own account. Choose someone else to send to.",
  errSendNotPerson: "That Account ID belongs to a service, not a person. Nothing was sent.",
  errSendNoAmount: "Enter an amount to send.",
  errSendMoreThanBalance: (amount: string) => `That's more than your balance of ${amount}.`,
  errSendRefused: "Agora, the issuer of these dollars, refused this payment. Nothing was sent.",
  errPayLinkOtherVersion: "This request belongs to a different version of NivPay and can't be paid here.",
  receiveTitle: "Receive",
  receiveHint: "Share your request link. Whoever opens it can pay you straight away.",
  requestAmountOptional: "Amount to ask for (optional)",
  shareRequestLink: "Share your request link",
  requestShareText: (name: string) => `Pay ${name} on NivPay.`,
  orShareAccountId: "Or share your Account ID",
  paymentsIn: "Payments in",
  noPaymentsYet: "Nothing yet. Payments show here once they're final, usually within a second.",
  paymentFrom: (from: string) => `From ${from}`,
  justArrived: "Just arrived",
  fromAgoraSettlement: "Agora's settlement, paid in another currency",
  receivedAnnounce: (amount: string, from: string) => `${amount} received from ${from}.`,
  errReceiveRead: "Couldn't check for payments just now. Trying again.",
  // Sending in another currency, through Agora's Instant Settlement
  theyReceive: "They receive",
  anotherCurrency: "Another currency",
  otherCurrencyHint: (symbol: string) => `${symbol} is a test currency from Agora, settled at a fixed rate the moment your payment is final.`,
  youSend: "You send",
  atLeast: (amount: string) => `At least ${amount}`,
  rate: "Rate",
  rateValue: (one: string) => `$1 = ${one}, fixed by Agora`,
  agoraFee: "Agora's fee",
  nivpayFeeNone: "No NivPay fee",
  atLeastHint: "If Agora's rate moves before this settles, it stops and your dollars stay with you.",
  oneTimeSetup: "Includes a one-time setup for sending in other currencies.",
  stepsLine: (steps: number) => (steps === 1 ? "One fingerprint, settled in one step." : `One fingerprint. It settles in ${steps} steps, each final before the next.`),
  sendAsAction: (amount: string, symbol: string) => `Send ${amount} as ${symbol}`,
  progressSetup: "One-time setup…",
  progressAllow: "Getting your dollars ready…",
  progressOf: (step: number, steps: number, what: string) => `Step ${step} of ${steps}. ${what}`,
  theyReceived: (amount: string) => `They received ${amount}.`,
  setupDoneNote: "Your one-time setup is done.",
  setupDoneButNotSent: "Your one-time setup is done, but the payment itself didn't go through. Your dollars didn't move.",
  errPairPaused: "Agora has paused sending in other currencies for now. Nothing was sent. Try again later, or send dollars.",
  errQuoteChanged: "The rate changed since you checked. Look over the new amounts before sending. Nothing was sent.",
  errLowLiquidity: "Agora can't settle that much in this currency right now. Try a smaller amount. Nothing was sent.",
  errNotEnoughForFees: "Your account can't cover the processing for this yet, and can't be topped up while it holds what it has. Send a smaller payment first, or try again later. Nothing was sent.",

  // A payment request (Live-Approve). Nobody "approves": deciders say yes.
  paymentRequest: "Payment request",
  openingRequest: "Opening the request…",
  wantsToPay: (who: string, amount: string, payee: string) => `${who} wants to pay ${amount} to ${payee}`,
  youAskedToPay: (amount: string, payee: string) => `You asked to pay ${amount} to ${payee}`,
  askedLine: (who: string, when: string) => `${who} · ${when}`,
  askedLineIn: (who: string, when: string, city: string) => `${who} · ${when} in ${city}`,
  nivpayFee: "NivPay fee",
  leftInPotAfter: "Left in the pot after",
  leftInPot: "Left in the pot",
  payeeLimit: (payee: string) => `${payee} limit`,
  limitOf: (used: string, cap: string) => `${used} of ${cap}`,
  chipAsked: "Asked",
  chipSaidYes: "Said yes",
  chipWaiting: "Waiting",
  moreYesPays: (more: number, payee: string) => (more === 1 ? `1 more yes pays ${payee} straight away.` : `${more} more yeses pay ${payee}.`),
  yesPaysNow: (k: number, n: number, payee: string) => `That's ${k} of ${n}. Paying ${payee} now.`,
  yourYesCounts: (more: number) => `Your yes counts. Waiting for ${more} more.`,
  yesCounted: "Your yes counts. Nothing moves until enough people say yes.",
  paidSeen: (names: string) => `Paid. ${names} will see it when they open the pot.`,
  paidAlone: "Paid.",
  paidLine: (amount: string, payee: string, total: string) => `Paid ${amount} to ${payee}. The pot has ${total}.`,
  sayYesAndPay: (payee: string) => `Say yes and pay ${payee}`,
  sayYes: "Say yes",
  sayingYes: "Saying yes…",
  payingNow: (payee: string) => `Paying ${payee}…`,
  notYet: "Not yet",
  needsYesesWithin: (k: number, days: number) => `Requests need ${k} ${k === 1 ? "yes" : "yeses"} within ${days} days, or they expire.`,
  takeBackYes: "Take back my yes",
  takingBack: "Taking it back…",
  tookBack: "Your yes is taken back. Nothing moved.",
  requestWithdrawn: "Whoever asked withdrew this request. Nothing was paid.",
  requestExpiredLine: (days: number) => `Not enough people said yes within ${days} days, so this request expired. Nothing was paid.`,
  requestClosedLine: "This pot is closed, so nothing more can be paid from it.",
  requestPausedLine: "Payments are paused on this pot, so nobody can say yes for now. A yes already given can still be taken back.",
  requestWatching: "Only the people who decide on this pot can say yes. You can follow it here.",
  cannotPayShort: (holds: string) => `Your yes would pay this, but the pot holds ${holds}, less than this and its fee. Once more goes in, you can say yes.`,
  cannotPayLimit: (payee: string, left: string) => `Your yes would pay this, but ${payee} can only be paid ${left} more from this pot.`,
  shareRequest: "Share the request",
  paymentRequestShareText: (pot: string) => `A payment from ${pot} is waiting for your yes on NivPay.`,
  requestDidNotGoThrough: "That didn't go through. Nothing moved.",
  requestTurnedDown: "That was turned down before it went through. Nothing has moved. You can try again.",
  personTime: (name: string, time: string) => `${name} · ${time}`,
  personAsked: (name: string) => `${name} · asked`,
  payeeSubAsked: (amount: string) => `asks ${amount}`,
  payeeSubPaid: (amount: string) => `paid ${amount}`,
  mapAsked: (holds: string, who: string, amount: string, payee: string) => `Map: the pot holds ${holds}. ${who} asked to pay ${amount} to ${payee}.`,
  mapPaid: (holds: string, amount: string, payee: string) => `Map: the pot holds ${holds}. ${amount} was paid to ${payee}.`,

  // Paying from a pot: refusals, each found before anything is signed
  errNotDecider: "Only the people who decide on this pot can ask for a payment or say yes to one. Nothing was sent.",
  errPayNoAmount: "Enter an amount to pay. Nothing was sent.",
  errOverLimit: (left: string, name: string) => `That's more than ${name} can still be paid from this pot: ${left} left. Nothing was sent.`,
  errOverLimitPlain: "That's more than this payee can still be paid from this pot. Nothing was sent.",
  errPotShort: (holds: string) => `The pot doesn't hold enough for this payment and its fee. It has ${holds}. Nothing was sent.`,
  errPotShortPlain: "The pot doesn't hold enough for this payment and its fee. Nothing was sent.",
  errPotStopped: "This pot is closed or paused, so nothing can be paid from it now. Nothing was sent.",
  errRequestExpired: "This request has expired. Ask again if it's still needed. Nothing was sent.",
  errRequestDecided: "This request isn't waiting for that any more: it's paid, withdrawn, or your answer already counts. Nothing was sent.",
  errRequestRefused: "This can't go through as things stand. Nothing was sent.",
  errRequestNotFound: "This payment request couldn't be found on this pot. Ask for the link again.",

  // Joining from an invite
  joinAPot: "Join a pot",
  joinAsDecider: (from: string, pot: string) => `${from} asked you to help decide payments from ${pot}.`,
  joinAsPayee: (from: string, pot: string, as: string) => `${from} wants ${pot} to be able to pay you, as ${as}.`,
  joinNeedsAccount: (from: string) => `${from} invited you to a pot. Make your account first, then you can join.`,
  makeMyReply: "Make my reply",
  replyTitle: "Send this back",
  replyBody: (from: string) => `Send this link back to ${from}. It shows this account is yours. It moves no money.`,
  sendTheReply: "Send the reply",
  copyTheLink: "Copy the link",
  replyShareText: (from: string) => `${from}, here is my reply for the pot on NivPay.`,
  replyThenHome: (from: string) => `Once ${from} makes the pot, it shows on your Home by itself. You won't need a link.`,
  invitedWaiting: (pot: string, from: string) => `Invited to ${pot} by ${from}. Waiting for the pot to be made.`,
  invitedTag: "Invited",
  invitedBy: (from: string) => `Invited by ${from}. Open it here, no link needed.`,
  alsoInIt: (people: string[]) => `Also in it: ${new Intl.ListFormat("en-GB", { style: "long", type: "conjunction" }).format(people)}.`,
  invitedShare: (amount: string) => `Suggested share ${amount}, not checked yet.`,
  replyAdded: (name: string) => `${name} joined as a decider.`,
  payeeReplyAdded: (name: string, as: string) => `${name} will be paid as ${as}.`,
  potNeedsAccount: "You were sent a pot. Make your account first, then you can chip in.",
  errLinkDamaged: "This link is damaged or incomplete. Ask for it again.",
  errReplyNotHere: "This reply is for a pot that isn't on this phone. Open it on the phone where the pot is being made.",
  errReplyUnverified: "This reply couldn't be checked, so it wasn't added. Ask them to send it again.",
  errReplyTooLate: "This pot is already made or being made, so nobody can join it now.",

  /** How a vendor or person is shown when a name alone isn't enough. */
  accountEnding: (id: string) => `account ending ${id.slice(-4)}`,
} as const;

/**
 * The connection banner. "Nothing has moved" is only true when no request of
 * ours is in flight; when that is unknown, it is not claimed.
 */
export function offlineMessage(requestsInFlight: number | undefined): string {
  return requestsInFlight === 0 ? copy.offlineNothingInFlight : copy.offlineRequestInFlight;
}

/**
 * The code table, mirrored in docs/ERROR-CODES.md. People read a code off the
 * phone; the table says what happened. Codes are stable: never reuse one.
 */
export const ERROR_CODES = {
  PREPARING: 10,
  IN_FLIGHT: 11,
  SETUP_UNREACHABLE: 12,
  SETUP_PAUSED: 13,
  SETUP_KEY_MALFORMED: 14,
  SETUP_KEY_MISMATCH: 15,
  SETUP_SEND_FAILED: 16,
  SETUP_READ_FAILED: 17,
  SETUP_LIMIT_REACHED: 18,
  SETUP_REFUSED: 19,
  SETUP_SLOW: 20,
  SETUP_REVERTED: 21,
  NOT_DECIDER: 22,
  PAY_NO_AMOUNT: 23,
  PAY_OVER_LIMIT: 24,
  PAY_POT_SHORT: 25,
  PAY_POT_STOPPED: 26,
  REQUEST_EXPIRED: 27,
  REQUEST_DECIDED: 28,
  REQUEST_REFUSED: 29,
  PASSKEY_CANCELLED: 30,
  PASSKEY_UNSUPPORTED: 31,
  BROWSER_MISSING_FEATURE: 32,
  WRONG_PASSKEY: 33,
  PASSKEY_TIMED_OUT: 34,
  PASSKEY_OTHER: 35,
  HOST_NOT_ALLOWED: 36,
  SIGNING: 41,
  SAVING: 42,
  CONFIRMING: 50,
  STUCK: 51,
  REVERTED: 52,
  SUPERSEDED: 53,
  MAY_STILL_GO_THROUGH: 54,
  NOTHING_STUCK: 55,
  REFUSED: 56,
  CLAIM_COOLDOWN: 60,
  CLAIM_CEILING: 61,
  CLAIM_REVERTED: 62,
  LINK_DAMAGED: 70,
  REPLY_NOT_HERE: 71,
  REPLY_UNVERIFIED: 72,
  CREATE_REFUSED: 73,
  REPLY_TOO_LATE: 74,
  POT_OTHER_VERSION: 75,
  POT_NOT_FOUND: 76,
  FIND_POTS_FAILED: 77,
  SEND_TO_SELF: 80,
  SEND_NOT_PERSON: 81,
  SEND_NO_AMOUNT: 82,
  SEND_MORE_THAN_BALANCE: 83,
  SEND_REFUSED: 84,
  PAY_LINK_OTHER_VERSION: 85,
  RECEIVE_READ_FAILED: 86,
  PAIR_PAUSED: 90,
  QUOTE_CHANGED: 91,
  LOW_LIQUIDITY: 92,
  NOT_ENOUGH_FOR_FEES: 93,
  UNKNOWN: 99,
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
